// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: estafette/ci/contracts/v1/build_params_config.proto

#ifndef PROTOBUF_INCLUDED_estafette_2fci_2fcontracts_2fv1_2fbuild_5fparams_5fconfig_2eproto
#define PROTOBUF_INCLUDED_estafette_2fci_2fcontracts_2fv1_2fbuild_5fparams_5fconfig_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_estafette_2fci_2fcontracts_2fv1_2fbuild_5fparams_5fconfig_2eproto 

namespace protobuf_estafette_2fci_2fcontracts_2fv1_2fbuild_5fparams_5fconfig_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_estafette_2fci_2fcontracts_2fv1_2fbuild_5fparams_5fconfig_2eproto
namespace estafette {
namespace ci {
namespace contracts {
namespace v1 {
class BuildParamsConfig;
class BuildParamsConfigDefaultTypeInternal;
extern BuildParamsConfigDefaultTypeInternal _BuildParamsConfig_default_instance_;
}  // namespace v1
}  // namespace contracts
}  // namespace ci
}  // namespace estafette
namespace google {
namespace protobuf {
template<> ::estafette::ci::contracts::v1::BuildParamsConfig* Arena::CreateMaybeMessage<::estafette::ci::contracts::v1::BuildParamsConfig>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace estafette {
namespace ci {
namespace contracts {
namespace v1 {

// ===================================================================

class BuildParamsConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:estafette.ci.contracts.v1.BuildParamsConfig) */ {
 public:
  BuildParamsConfig();
  virtual ~BuildParamsConfig();

  BuildParamsConfig(const BuildParamsConfig& from);

  inline BuildParamsConfig& operator=(const BuildParamsConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BuildParamsConfig(BuildParamsConfig&& from) noexcept
    : BuildParamsConfig() {
    *this = ::std::move(from);
  }

  inline BuildParamsConfig& operator=(BuildParamsConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BuildParamsConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BuildParamsConfig* internal_default_instance() {
    return reinterpret_cast<const BuildParamsConfig*>(
               &_BuildParamsConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(BuildParamsConfig* other);
  friend void swap(BuildParamsConfig& a, BuildParamsConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BuildParamsConfig* New() const final {
    return CreateMaybeMessage<BuildParamsConfig>(NULL);
  }

  BuildParamsConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BuildParamsConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BuildParamsConfig& from);
  void MergeFrom(const BuildParamsConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BuildParamsConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 build_id = 1;
  void clear_build_id();
  static const int kBuildIdFieldNumber = 1;
  ::google::protobuf::int64 build_id() const;
  void set_build_id(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:estafette.ci.contracts.v1.BuildParamsConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 build_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_estafette_2fci_2fcontracts_2fv1_2fbuild_5fparams_5fconfig_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BuildParamsConfig

// int64 build_id = 1;
inline void BuildParamsConfig::clear_build_id() {
  build_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 BuildParamsConfig::build_id() const {
  // @@protoc_insertion_point(field_get:estafette.ci.contracts.v1.BuildParamsConfig.build_id)
  return build_id_;
}
inline void BuildParamsConfig::set_build_id(::google::protobuf::int64 value) {
  
  build_id_ = value;
  // @@protoc_insertion_point(field_set:estafette.ci.contracts.v1.BuildParamsConfig.build_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace contracts
}  // namespace ci
}  // namespace estafette

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_estafette_2fci_2fcontracts_2fv1_2fbuild_5fparams_5fconfig_2eproto
