// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/contracts.v1/container_repository_credential_config.proto

#ifndef PROTOBUF_INCLUDED_protos_2fcontracts_2ev1_2fcontainer_5frepository_5fcredential_5fconfig_2eproto
#define PROTOBUF_INCLUDED_protos_2fcontracts_2ev1_2fcontainer_5frepository_5fcredential_5fconfig_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_protos_2fcontracts_2ev1_2fcontainer_5frepository_5fcredential_5fconfig_2eproto 

namespace protobuf_protos_2fcontracts_2ev1_2fcontainer_5frepository_5fcredential_5fconfig_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_protos_2fcontracts_2ev1_2fcontainer_5frepository_5fcredential_5fconfig_2eproto
namespace contracts {
namespace v1 {
class ContainerRepositoryCredentialConfig;
class ContainerRepositoryCredentialConfigDefaultTypeInternal;
extern ContainerRepositoryCredentialConfigDefaultTypeInternal _ContainerRepositoryCredentialConfig_default_instance_;
}  // namespace v1
}  // namespace contracts
namespace google {
namespace protobuf {
template<> ::contracts::v1::ContainerRepositoryCredentialConfig* Arena::CreateMaybeMessage<::contracts::v1::ContainerRepositoryCredentialConfig>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace contracts {
namespace v1 {

// ===================================================================

class ContainerRepositoryCredentialConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:contracts.v1.ContainerRepositoryCredentialConfig) */ {
 public:
  ContainerRepositoryCredentialConfig();
  virtual ~ContainerRepositoryCredentialConfig();

  ContainerRepositoryCredentialConfig(const ContainerRepositoryCredentialConfig& from);

  inline ContainerRepositoryCredentialConfig& operator=(const ContainerRepositoryCredentialConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ContainerRepositoryCredentialConfig(ContainerRepositoryCredentialConfig&& from) noexcept
    : ContainerRepositoryCredentialConfig() {
    *this = ::std::move(from);
  }

  inline ContainerRepositoryCredentialConfig& operator=(ContainerRepositoryCredentialConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ContainerRepositoryCredentialConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ContainerRepositoryCredentialConfig* internal_default_instance() {
    return reinterpret_cast<const ContainerRepositoryCredentialConfig*>(
               &_ContainerRepositoryCredentialConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ContainerRepositoryCredentialConfig* other);
  friend void swap(ContainerRepositoryCredentialConfig& a, ContainerRepositoryCredentialConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ContainerRepositoryCredentialConfig* New() const final {
    return CreateMaybeMessage<ContainerRepositoryCredentialConfig>(NULL);
  }

  ContainerRepositoryCredentialConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ContainerRepositoryCredentialConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ContainerRepositoryCredentialConfig& from);
  void MergeFrom(const ContainerRepositoryCredentialConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ContainerRepositoryCredentialConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string repository = 1;
  void clear_repository();
  static const int kRepositoryFieldNumber = 1;
  const ::std::string& repository() const;
  void set_repository(const ::std::string& value);
  #if LANG_CXX11
  void set_repository(::std::string&& value);
  #endif
  void set_repository(const char* value);
  void set_repository(const char* value, size_t size);
  ::std::string* mutable_repository();
  ::std::string* release_repository();
  void set_allocated_repository(::std::string* repository);

  // string username = 2;
  void clear_username();
  static const int kUsernameFieldNumber = 2;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  #if LANG_CXX11
  void set_username(::std::string&& value);
  #endif
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // string password = 3;
  void clear_password();
  static const int kPasswordFieldNumber = 3;
  const ::std::string& password() const;
  void set_password(const ::std::string& value);
  #if LANG_CXX11
  void set_password(::std::string&& value);
  #endif
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  ::std::string* mutable_password();
  ::std::string* release_password();
  void set_allocated_password(::std::string* password);

  // @@protoc_insertion_point(class_scope:contracts.v1.ContainerRepositoryCredentialConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr repository_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  ::google::protobuf::internal::ArenaStringPtr password_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_protos_2fcontracts_2ev1_2fcontainer_5frepository_5fcredential_5fconfig_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ContainerRepositoryCredentialConfig

// string repository = 1;
inline void ContainerRepositoryCredentialConfig::clear_repository() {
  repository_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ContainerRepositoryCredentialConfig::repository() const {
  // @@protoc_insertion_point(field_get:contracts.v1.ContainerRepositoryCredentialConfig.repository)
  return repository_.GetNoArena();
}
inline void ContainerRepositoryCredentialConfig::set_repository(const ::std::string& value) {
  
  repository_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:contracts.v1.ContainerRepositoryCredentialConfig.repository)
}
#if LANG_CXX11
inline void ContainerRepositoryCredentialConfig::set_repository(::std::string&& value) {
  
  repository_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:contracts.v1.ContainerRepositoryCredentialConfig.repository)
}
#endif
inline void ContainerRepositoryCredentialConfig::set_repository(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  repository_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:contracts.v1.ContainerRepositoryCredentialConfig.repository)
}
inline void ContainerRepositoryCredentialConfig::set_repository(const char* value, size_t size) {
  
  repository_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:contracts.v1.ContainerRepositoryCredentialConfig.repository)
}
inline ::std::string* ContainerRepositoryCredentialConfig::mutable_repository() {
  
  // @@protoc_insertion_point(field_mutable:contracts.v1.ContainerRepositoryCredentialConfig.repository)
  return repository_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ContainerRepositoryCredentialConfig::release_repository() {
  // @@protoc_insertion_point(field_release:contracts.v1.ContainerRepositoryCredentialConfig.repository)
  
  return repository_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ContainerRepositoryCredentialConfig::set_allocated_repository(::std::string* repository) {
  if (repository != NULL) {
    
  } else {
    
  }
  repository_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), repository);
  // @@protoc_insertion_point(field_set_allocated:contracts.v1.ContainerRepositoryCredentialConfig.repository)
}

// string username = 2;
inline void ContainerRepositoryCredentialConfig::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ContainerRepositoryCredentialConfig::username() const {
  // @@protoc_insertion_point(field_get:contracts.v1.ContainerRepositoryCredentialConfig.username)
  return username_.GetNoArena();
}
inline void ContainerRepositoryCredentialConfig::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:contracts.v1.ContainerRepositoryCredentialConfig.username)
}
#if LANG_CXX11
inline void ContainerRepositoryCredentialConfig::set_username(::std::string&& value) {
  
  username_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:contracts.v1.ContainerRepositoryCredentialConfig.username)
}
#endif
inline void ContainerRepositoryCredentialConfig::set_username(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:contracts.v1.ContainerRepositoryCredentialConfig.username)
}
inline void ContainerRepositoryCredentialConfig::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:contracts.v1.ContainerRepositoryCredentialConfig.username)
}
inline ::std::string* ContainerRepositoryCredentialConfig::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:contracts.v1.ContainerRepositoryCredentialConfig.username)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ContainerRepositoryCredentialConfig::release_username() {
  // @@protoc_insertion_point(field_release:contracts.v1.ContainerRepositoryCredentialConfig.username)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ContainerRepositoryCredentialConfig::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:contracts.v1.ContainerRepositoryCredentialConfig.username)
}

// string password = 3;
inline void ContainerRepositoryCredentialConfig::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ContainerRepositoryCredentialConfig::password() const {
  // @@protoc_insertion_point(field_get:contracts.v1.ContainerRepositoryCredentialConfig.password)
  return password_.GetNoArena();
}
inline void ContainerRepositoryCredentialConfig::set_password(const ::std::string& value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:contracts.v1.ContainerRepositoryCredentialConfig.password)
}
#if LANG_CXX11
inline void ContainerRepositoryCredentialConfig::set_password(::std::string&& value) {
  
  password_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:contracts.v1.ContainerRepositoryCredentialConfig.password)
}
#endif
inline void ContainerRepositoryCredentialConfig::set_password(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:contracts.v1.ContainerRepositoryCredentialConfig.password)
}
inline void ContainerRepositoryCredentialConfig::set_password(const char* value, size_t size) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:contracts.v1.ContainerRepositoryCredentialConfig.password)
}
inline ::std::string* ContainerRepositoryCredentialConfig::mutable_password() {
  
  // @@protoc_insertion_point(field_mutable:contracts.v1.ContainerRepositoryCredentialConfig.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ContainerRepositoryCredentialConfig::release_password() {
  // @@protoc_insertion_point(field_release:contracts.v1.ContainerRepositoryCredentialConfig.password)
  
  return password_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ContainerRepositoryCredentialConfig::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:contracts.v1.ContainerRepositoryCredentialConfig.password)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace contracts

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_protos_2fcontracts_2ev1_2fcontainer_5frepository_5fcredential_5fconfig_2eproto
