// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manifest.v1/estafette_custom_version.proto

#include "manifest.v1/estafette_custom_version.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace manifest {
namespace v1 {
class EstafetteCustomVersionDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<EstafetteCustomVersion>
      _instance;
} _EstafetteCustomVersion_default_instance_;
}  // namespace v1
}  // namespace manifest
namespace protobuf_manifest_2ev1_2festafette_5fcustom_5fversion_2eproto {
static void InitDefaultsEstafetteCustomVersion() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::manifest::v1::_EstafetteCustomVersion_default_instance_;
    new (ptr) ::manifest::v1::EstafetteCustomVersion();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::manifest::v1::EstafetteCustomVersion::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_EstafetteCustomVersion =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsEstafetteCustomVersion}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_EstafetteCustomVersion.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::manifest::v1::EstafetteCustomVersion, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::manifest::v1::EstafetteCustomVersion, label_template_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::manifest::v1::EstafetteCustomVersion)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::manifest::v1::_EstafetteCustomVersion_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "manifest.v1/estafette_custom_version.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n*manifest.v1/estafette_custom_version.p"
      "roto\022\013manifest.v1\"0\n\026EstafetteCustomVers"
      "ion\022\026\n\016label_template\030\001 \001(\tBx\n\033io.estafe"
      "tte.ci.manifest.v1Z>github.com/estafette"
      "/estafette-ci-contracts-golang/manifest_"
      "v1\252\002\030Estafette.CI.Manifest.V1b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 237);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "manifest.v1/estafette_custom_version.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_manifest_2ev1_2festafette_5fcustom_5fversion_2eproto
namespace manifest {
namespace v1 {

// ===================================================================

void EstafetteCustomVersion::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int EstafetteCustomVersion::kLabelTemplateFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

EstafetteCustomVersion::EstafetteCustomVersion()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_manifest_2ev1_2festafette_5fcustom_5fversion_2eproto::scc_info_EstafetteCustomVersion.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:manifest.v1.EstafetteCustomVersion)
}
EstafetteCustomVersion::EstafetteCustomVersion(const EstafetteCustomVersion& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  label_template_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.label_template().size() > 0) {
    label_template_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.label_template_);
  }
  // @@protoc_insertion_point(copy_constructor:manifest.v1.EstafetteCustomVersion)
}

void EstafetteCustomVersion::SharedCtor() {
  label_template_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

EstafetteCustomVersion::~EstafetteCustomVersion() {
  // @@protoc_insertion_point(destructor:manifest.v1.EstafetteCustomVersion)
  SharedDtor();
}

void EstafetteCustomVersion::SharedDtor() {
  label_template_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void EstafetteCustomVersion::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* EstafetteCustomVersion::descriptor() {
  ::protobuf_manifest_2ev1_2festafette_5fcustom_5fversion_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_manifest_2ev1_2festafette_5fcustom_5fversion_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const EstafetteCustomVersion& EstafetteCustomVersion::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_manifest_2ev1_2festafette_5fcustom_5fversion_2eproto::scc_info_EstafetteCustomVersion.base);
  return *internal_default_instance();
}


void EstafetteCustomVersion::Clear() {
// @@protoc_insertion_point(message_clear_start:manifest.v1.EstafetteCustomVersion)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  label_template_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool EstafetteCustomVersion::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:manifest.v1.EstafetteCustomVersion)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string label_template = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_label_template()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->label_template().data(), static_cast<int>(this->label_template().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "manifest.v1.EstafetteCustomVersion.label_template"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:manifest.v1.EstafetteCustomVersion)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:manifest.v1.EstafetteCustomVersion)
  return false;
#undef DO_
}

void EstafetteCustomVersion::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:manifest.v1.EstafetteCustomVersion)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string label_template = 1;
  if (this->label_template().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->label_template().data(), static_cast<int>(this->label_template().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "manifest.v1.EstafetteCustomVersion.label_template");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->label_template(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:manifest.v1.EstafetteCustomVersion)
}

::google::protobuf::uint8* EstafetteCustomVersion::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:manifest.v1.EstafetteCustomVersion)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string label_template = 1;
  if (this->label_template().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->label_template().data(), static_cast<int>(this->label_template().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "manifest.v1.EstafetteCustomVersion.label_template");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->label_template(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:manifest.v1.EstafetteCustomVersion)
  return target;
}

size_t EstafetteCustomVersion::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:manifest.v1.EstafetteCustomVersion)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string label_template = 1;
  if (this->label_template().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->label_template());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void EstafetteCustomVersion::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:manifest.v1.EstafetteCustomVersion)
  GOOGLE_DCHECK_NE(&from, this);
  const EstafetteCustomVersion* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const EstafetteCustomVersion>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:manifest.v1.EstafetteCustomVersion)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:manifest.v1.EstafetteCustomVersion)
    MergeFrom(*source);
  }
}

void EstafetteCustomVersion::MergeFrom(const EstafetteCustomVersion& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:manifest.v1.EstafetteCustomVersion)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.label_template().size() > 0) {

    label_template_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.label_template_);
  }
}

void EstafetteCustomVersion::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:manifest.v1.EstafetteCustomVersion)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EstafetteCustomVersion::CopyFrom(const EstafetteCustomVersion& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:manifest.v1.EstafetteCustomVersion)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EstafetteCustomVersion::IsInitialized() const {
  return true;
}

void EstafetteCustomVersion::Swap(EstafetteCustomVersion* other) {
  if (other == this) return;
  InternalSwap(other);
}
void EstafetteCustomVersion::InternalSwap(EstafetteCustomVersion* other) {
  using std::swap;
  label_template_.Swap(&other->label_template_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata EstafetteCustomVersion::GetMetadata() const {
  protobuf_manifest_2ev1_2festafette_5fcustom_5fversion_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_manifest_2ev1_2festafette_5fcustom_5fversion_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace manifest
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::manifest::v1::EstafetteCustomVersion* Arena::CreateMaybeMessage< ::manifest::v1::EstafetteCustomVersion >(Arena* arena) {
  return Arena::CreateInternal< ::manifest::v1::EstafetteCustomVersion >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
