// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manifest.v1/estafette_version.proto

#include "manifest.v1/estafette_version.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_manifest_2ev1_2festafette_5fcustom_5fversion_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_manifest_2ev1_2festafette_5fcustom_5fversion_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_EstafetteCustomVersion;
}  // namespace protobuf_manifest_2ev1_2festafette_5fcustom_5fversion_2eproto
namespace protobuf_manifest_2ev1_2festafette_5fsemver_5fversion_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_manifest_2ev1_2festafette_5fsemver_5fversion_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_EstafetteSemverVersion;
}  // namespace protobuf_manifest_2ev1_2festafette_5fsemver_5fversion_2eproto
namespace manifest {
namespace v1 {
class EstafetteVersionDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<EstafetteVersion>
      _instance;
} _EstafetteVersion_default_instance_;
}  // namespace v1
}  // namespace manifest
namespace protobuf_manifest_2ev1_2festafette_5fversion_2eproto {
static void InitDefaultsEstafetteVersion() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::manifest::v1::_EstafetteVersion_default_instance_;
    new (ptr) ::manifest::v1::EstafetteVersion();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::manifest::v1::EstafetteVersion::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_EstafetteVersion =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsEstafetteVersion}, {
      &protobuf_manifest_2ev1_2festafette_5fsemver_5fversion_2eproto::scc_info_EstafetteSemverVersion.base,
      &protobuf_manifest_2ev1_2festafette_5fcustom_5fversion_2eproto::scc_info_EstafetteCustomVersion.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_EstafetteVersion.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::manifest::v1::EstafetteVersion, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::manifest::v1::EstafetteVersion, semver_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::manifest::v1::EstafetteVersion, custom_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::manifest::v1::EstafetteVersion)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::manifest::v1::_EstafetteVersion_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "manifest.v1/estafette_version.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n#manifest.v1/estafette_version.proto\022\013m"
      "anifest.v1\032*manifest.v1/estafette_custom"
      "_version.proto\032*manifest.v1/estafette_se"
      "mver_version.proto\"|\n\020EstafetteVersion\0223"
      "\n\006semver\030\001 \001(\0132#.manifest.v1.EstafetteSe"
      "mverVersion\0223\n\006custom\030\002 \001(\0132#.manifest.v"
      "1.EstafetteCustomVersionB[Z>github.com/e"
      "stafette/estafette-ci-contracts-golang/m"
      "anifest_v1\252\002\030Estafette.CI.Manifest.V1b\006p"
      "roto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 365);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "manifest.v1/estafette_version.proto", &protobuf_RegisterTypes);
  ::protobuf_manifest_2ev1_2festafette_5fcustom_5fversion_2eproto::AddDescriptors();
  ::protobuf_manifest_2ev1_2festafette_5fsemver_5fversion_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_manifest_2ev1_2festafette_5fversion_2eproto
namespace manifest {
namespace v1 {

// ===================================================================

void EstafetteVersion::InitAsDefaultInstance() {
  ::manifest::v1::_EstafetteVersion_default_instance_._instance.get_mutable()->semver_ = const_cast< ::manifest::v1::EstafetteSemverVersion*>(
      ::manifest::v1::EstafetteSemverVersion::internal_default_instance());
  ::manifest::v1::_EstafetteVersion_default_instance_._instance.get_mutable()->custom_ = const_cast< ::manifest::v1::EstafetteCustomVersion*>(
      ::manifest::v1::EstafetteCustomVersion::internal_default_instance());
}
void EstafetteVersion::clear_semver() {
  if (GetArenaNoVirtual() == NULL && semver_ != NULL) {
    delete semver_;
  }
  semver_ = NULL;
}
void EstafetteVersion::clear_custom() {
  if (GetArenaNoVirtual() == NULL && custom_ != NULL) {
    delete custom_;
  }
  custom_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int EstafetteVersion::kSemverFieldNumber;
const int EstafetteVersion::kCustomFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

EstafetteVersion::EstafetteVersion()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_manifest_2ev1_2festafette_5fversion_2eproto::scc_info_EstafetteVersion.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:manifest.v1.EstafetteVersion)
}
EstafetteVersion::EstafetteVersion(const EstafetteVersion& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_semver()) {
    semver_ = new ::manifest::v1::EstafetteSemverVersion(*from.semver_);
  } else {
    semver_ = NULL;
  }
  if (from.has_custom()) {
    custom_ = new ::manifest::v1::EstafetteCustomVersion(*from.custom_);
  } else {
    custom_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:manifest.v1.EstafetteVersion)
}

void EstafetteVersion::SharedCtor() {
  ::memset(&semver_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&custom_) -
      reinterpret_cast<char*>(&semver_)) + sizeof(custom_));
}

EstafetteVersion::~EstafetteVersion() {
  // @@protoc_insertion_point(destructor:manifest.v1.EstafetteVersion)
  SharedDtor();
}

void EstafetteVersion::SharedDtor() {
  if (this != internal_default_instance()) delete semver_;
  if (this != internal_default_instance()) delete custom_;
}

void EstafetteVersion::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* EstafetteVersion::descriptor() {
  ::protobuf_manifest_2ev1_2festafette_5fversion_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_manifest_2ev1_2festafette_5fversion_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const EstafetteVersion& EstafetteVersion::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_manifest_2ev1_2festafette_5fversion_2eproto::scc_info_EstafetteVersion.base);
  return *internal_default_instance();
}


void EstafetteVersion::Clear() {
// @@protoc_insertion_point(message_clear_start:manifest.v1.EstafetteVersion)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && semver_ != NULL) {
    delete semver_;
  }
  semver_ = NULL;
  if (GetArenaNoVirtual() == NULL && custom_ != NULL) {
    delete custom_;
  }
  custom_ = NULL;
  _internal_metadata_.Clear();
}

bool EstafetteVersion::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:manifest.v1.EstafetteVersion)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .manifest.v1.EstafetteSemverVersion semver = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_semver()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .manifest.v1.EstafetteCustomVersion custom = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_custom()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:manifest.v1.EstafetteVersion)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:manifest.v1.EstafetteVersion)
  return false;
#undef DO_
}

void EstafetteVersion::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:manifest.v1.EstafetteVersion)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .manifest.v1.EstafetteSemverVersion semver = 1;
  if (this->has_semver()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_semver(), output);
  }

  // .manifest.v1.EstafetteCustomVersion custom = 2;
  if (this->has_custom()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_custom(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:manifest.v1.EstafetteVersion)
}

::google::protobuf::uint8* EstafetteVersion::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:manifest.v1.EstafetteVersion)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .manifest.v1.EstafetteSemverVersion semver = 1;
  if (this->has_semver()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_semver(), deterministic, target);
  }

  // .manifest.v1.EstafetteCustomVersion custom = 2;
  if (this->has_custom()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_custom(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:manifest.v1.EstafetteVersion)
  return target;
}

size_t EstafetteVersion::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:manifest.v1.EstafetteVersion)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .manifest.v1.EstafetteSemverVersion semver = 1;
  if (this->has_semver()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *semver_);
  }

  // .manifest.v1.EstafetteCustomVersion custom = 2;
  if (this->has_custom()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *custom_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void EstafetteVersion::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:manifest.v1.EstafetteVersion)
  GOOGLE_DCHECK_NE(&from, this);
  const EstafetteVersion* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const EstafetteVersion>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:manifest.v1.EstafetteVersion)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:manifest.v1.EstafetteVersion)
    MergeFrom(*source);
  }
}

void EstafetteVersion::MergeFrom(const EstafetteVersion& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:manifest.v1.EstafetteVersion)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_semver()) {
    mutable_semver()->::manifest::v1::EstafetteSemverVersion::MergeFrom(from.semver());
  }
  if (from.has_custom()) {
    mutable_custom()->::manifest::v1::EstafetteCustomVersion::MergeFrom(from.custom());
  }
}

void EstafetteVersion::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:manifest.v1.EstafetteVersion)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EstafetteVersion::CopyFrom(const EstafetteVersion& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:manifest.v1.EstafetteVersion)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EstafetteVersion::IsInitialized() const {
  return true;
}

void EstafetteVersion::Swap(EstafetteVersion* other) {
  if (other == this) return;
  InternalSwap(other);
}
void EstafetteVersion::InternalSwap(EstafetteVersion* other) {
  using std::swap;
  swap(semver_, other->semver_);
  swap(custom_, other->custom_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata EstafetteVersion::GetMetadata() const {
  protobuf_manifest_2ev1_2festafette_5fversion_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_manifest_2ev1_2festafette_5fversion_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace manifest
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::manifest::v1::EstafetteVersion* Arena::CreateMaybeMessage< ::manifest::v1::EstafetteVersion >(Arena* arena) {
  return Arena::CreateInternal< ::manifest::v1::EstafetteVersion >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
